name: CI

on:
  push:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "23.3"

    - name: Build
      run: cargo build --verbose

  publish:
      name: Publish Android library
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

        - name: Install Protoc
          uses: arduino/setup-protoc@v3
          with:
            version: "23.3"

        - name: Publish package
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            rustup target install armv7-linux-androideabi aarch64-linux-android i686-linux-android
            cd bindings/kotlin
            ./gradlew clean build publish
