name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        default: "0.0.0"
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-dotnet:
    name: Publish Windows .NET NuGet
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Run setup
      shell: pwsh
      run: |
          .\setup.ps1
  
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: "23.3"

    - name: Build
      shell: pwsh
      run: |
        .\generate-csharp.ps1
        dotnet build -c Release .\bindings\csharp\InterShareSdk

    - name: Pack
      run: dotnet pack bindings/csharp/InterShareSdk/InterShareSdk.csproj -c Release -p:PackageVersion='${{ github.event.inputs.version }}' --output packages

    - name: Upload to GitHub registry
      run: |
        dotnet nuget add source --username InterShare --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/InterShare/index.json"
        dotnet nuget push "packages/InterShareSdk.${{ github.event.inputs.version }}.nupkg" --api-key "${{ secrets.GITHUB_TOKEN }}" --source "github"

  publish-android:
      name: Publish Android library
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - uses: nttld/setup-ndk@v1
          id: setup-ndk
          with:
            ndk-version: r26c
            add-to-path: true
            link-to-sdk: true

        - name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

        - name: Install Protoc
          uses: arduino/setup-protoc@v3
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            version: "23.3"

        - name: Publish package
          env:
            ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
            GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            VERSION: ${{ github.event.inputs.version }}
          run: |
            echo $ANDROID_NDK_HOME
            echo $ANDROID_NDK_TOOLCHAIN_DIR
            rustup target add x86_64-linux-android x86_64-unknown-linux-gnu aarch64-linux-android armv7-linux-androideabi i686-linux-android
            cd bindings/kotlin
            ./gradlew clean build publish

  create-release:
    name: Create Realase
    needs: [publish-android, publish-dotnet]
    runs-on: ubuntu-latest
    steps:
    - name: Create Release strings
      id: release_strings
      run: |
        echo "RELEASE_TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        echo "RELEASE_NAME=Version ${{ github.event.inputs.version }}" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: ${{ env.RELEASE_NAME }}