name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        default: "0.0.0"
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
      name: Publish Android library
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - uses: nttld/setup-ndk@v1
          id: setup-ndk
          with:
            ndk-version: r26c
            add-to-path: true

        - name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

        - name: Install Protoc
          uses: arduino/setup-protoc@v3
          with:
            version: "23.3"

        - name: Publish package
          env:
            ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
            GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            VERSION: ${{ github.event.inputs.version }}
          run: |
            echo $ANDROID_NDK_HOME
            echo $ANDROID_NDK_TOOLCHAIN_DIR
            rustup target add x86_64-linux-android x86_64-unknown-linux-gnu aarch64-linux-android armv7-linux-androideabi i686-linux-android
            cd bindings/kotlin
            ./gradlew clean build publish
